name: example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.1.0
  collection: 
  cupertino_icons: ^1.0.9
  provider: ^6.1.5+1
  sheet:
    path: ../
  go_router: ^18.0.1
  cupertino_ui: ^1.1.0
  material_ui: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.1.0

flutter:
  uses-material-design: true

  assets:
   - assets/
