name: sheet
description: A fully customizable draggable bottom sheet.
version: 1.0.1
homepage: https://github.com/jamesblasco/modal_bottom_sheet

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  material_ui: ^1.3.0
  cupertino_ui: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  lints: ">=6.1.0"

flutter: